### ISSUE TITLE
Некорректно разбираются параметры если значение содержит знак "="

### ISSUE THREAD

**Issue by arkuznetsov** [vbondarevsky/1connector#17]
Некорректно разбираются параметры если значение содержит знак "=", все что после "=" в значении параметра отбрасывается.

**Comment by arkuznetsov** [comment]
@vbondarevsky Когда ждать в хабе?

**Comment by vbondarevsky** [comment]
> @vbondarevsky Когда ждать в хабе?

На выходных опубликую. Хочу еще кое-что включить в релиз

**Comment by vbondarevsky** [comment]
Опубликовано
